### ISSUE TITLE
Repeated mentions in predictions

### ISSUE THREAD

**Issue by andreasvc** [shtoshni/fast-coref#3]
I get the following error message from the scorer:
```
Using CoNLL scorer
[...]
.//../../coref_resources/reference-coreference-scorers/scorer.pl
Found too many repeated mentions (> 10) in the response, so refusing to score. Please fix the output.
```
This message occurs when a span has multiple clusters, e.g.,:
```
doc   0   14   hemzelf   VNW[pers,pron,obl,nadr,3m,ev,masc]   *)))))   -   -   -   -   *   (484)|(484)
```
Interestingly, `hemzelf` (himself) is a word made up of two morphemes that are also words on their own, so this might be the reason this happens. In this case the same cluster is assigned twice, but there are also cases where different clusters are assigned to the same span.

The error messages by [coval](https://github.com/ns-moosavi/coval/) are a bit more informative and also tell you which clusters have duplicate spans.

**Comment by shtoshni** [comment]
Thanks, I did run into these issues sometimes but the python script was still able to output numbers. Do you have the logs for this run i.e. the CoNLL outputted by the script?

**Comment by andreasvc** [comment]
The CoNLL scorer is a Perl script, not a Python script, and it is obviously important that the Perl script runs without error because it is the reference scorer for the coreference task. I could dig up the CoNLL output, but I don't think it is helpful, the error message is very clear. Can't you just avoid duplicates by putting the mentions in a set/dict rather than a list?

**Comment by shtoshni** [comment]
Right, I use the official [CoNLL scorer](https://github.com/shtoshni/fast-coref/blob/main/src/utils_evaluate.py#L141), and in rare cases when the script fails (mostly due to some bracketing issues), there's the python implementation by [Kenton Lee](https://github.com/shtoshni/fast-coref/blob/main/src/coref_utils/conll.py) which handles these cases more gracefully. 

So repeated mentions actually points to a deeper problem because the mention proposal module should in theory never repeat a mention. I mostly remember the bracketing issue which could be down to the fact that we don't enforce word boundaries on the proposed mentions. I'm looking into this.

**Comment by andreasvc** [comment]
Thanks a lot! My previous message was a bit grumpy ...

As I wrote in the initial issue, I do suspect it might have something to do with word boundaries and the mapping of BERT subwords to original words. The word "hemzelf" can be decomposed into "hem" and "zelf" which are also valid words on their own.

I'll share the CoNLL output privately (copyrighted material).

**Comment by shtoshni** [comment]
I'm closing the issue because I think the update handles this issue. Feel free to open this if there are lingering issues.
